services:
  justasimpledash:
    build:
      context: .
      args:
        # This reads the variable from the .env file
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID}
    container_name: justasimpledash
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mounts the config directory as read-only for safety
      - ./config:/app/config:ro