services:
  dashboard:
    build:
      context: .
      args:
        - DOCKER_GROUP_ID=$(stat -c '%g' /var/run/docker.sock)
    container_name: my-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Ensure both config and icons are available
      - ./config:/app/config:ro # 'ro' makes it read-only for safety